# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XGYnZbfQgZhkTr7vUOgow73UOswG43j
"""

import librosa
import matplotlib.pyplot as plt
import librosa.display
import numpy as np
import os

def wav_2_mel(wav_file_path, mel_directory):
  y, sr = librosa.load(wav_file_path) # your file

  S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=8000)
  librosa.display.specshow(librosa.power_to_db(S, ref=np.max), fmax=8000)
  name = os.path.basename(wav_file_path).split('.')[0]
  plt.savefig(mel_directory + "/"+ name + ".png")

wav_2_mel("/content/files/voice.wav", "/content/files")